apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermarket-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: supermarket-app
  template:
    metadata:
      labels:
        app: supermarket-app
    spec:
      containers:
      - name: supermarket-app
        image: 547223838688.dkr.ecr.us-west-2.amazonaws.com/supermarketapp2:latest
        ports:
        - containerPort: 8080
